"""Provider contract regressions, exercised at actual HTTP and Fluent boundaries."""
import copy
import json
import os
from pathlib import Path
import tempfile
import unittest

os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')
from PyQt5.QtWidgets import QApplication
from core.api_client import ApiClient, GROK, V3_MODELS
from core.config_manager import ConfigManager, DEFAULT_CONFIG
from core.task_manager import TaskWorker
from test_http_clients import LocalServer
from ui.widgets.params_card import ParamsCard
from ui.pages.settings_page import SettingsPage


def params(**overrides):
    result = dict(duration=8, aspect_ratio='9:16', resolution='1080p', generate_audio=False, seed='')
    result.update(overrides)
    return result


class ModelContractTests(unittest.TestCase):
    def test_h3_exact_fixed_sizes_and_no_ratio_or_empty_media(self):
        # These values are transcribed from the provider's H3 table, not generated by the implementation.
        sizes = {
            '16:9': ['864x480', '1376x768', '1920x1088'],
            '9:16': ['480x864', '768x1376', '1088x1920'],
            '1:1': ['640x640', '1024x1024', '1440x1440'],
            '2:3': ['544x800', '832x1248', '1184x1760'],
            '3:2': ['800x544', '1248x832', '1760x1184'],
            '3:4': ['576x736', '896x1184', '1248x1664'],
            '4:3': ['736x576', '1184x896', '1664x1248'],
            '21:9': ['992x416', '1568x672', '2208x960'],
        }
        with LocalServer() as server:
            client = ApiClient(server.base, 'test')
            self.addCleanup(client.close)
            for ratio, exact_sizes in sizes.items():
                for resolution, exact in zip(['480p', '768p', '1080p'], exact_sizes):
                    with self.subTest(ratio=ratio, resolution=resolution):
                        client.create_task('MiniMax-H3', '镜头推进', ['https://example.com/ref.jpg'], params(aspect_ratio=ratio, resolution=resolution))
                        self.assertEqual(json.loads(server.calls[-1][2]), dict(model='MiniMax-H3', prompt='镜头推进',
                            workflow_id='multi-reference', seconds=8, size=exact, images=['https://example.com/ref.jpg']))

    def test_h3_high_resolution_keeps_ratio_and_workflow_depends_on_materials(self):
        with LocalServer() as server:
            client = ApiClient(server.base, 'test'); self.addCleanup(client.close)
            for size in ('2K', '4K'):
                client.create_task('MiniMax-H3', 'text', [], params(resolution=size))
                self.assertEqual(json.loads(server.calls[-1][2]), dict(model='MiniMax-H3', prompt='text',
                    workflow_id='text-to-video', seconds=8, size=size, aspect_ratio='9:16'))
                client.create_task('MiniMax-H3', 'text', ['https://example.com/ref.jpg'], params(resolution=size))
                self.assertEqual(json.loads(server.calls[-1][2])['workflow_id'], 'multi-reference')

    def test_json_models_match_documented_fields_and_audio_seed_types(self):
        with LocalServer() as server:
            client = ApiClient(server.base, 'test'); self.addCleanup(client.close)
            client.create_task('video-v1', 'text', [], params(duration=10))
            self.assertEqual(server.calls[-1][0], '/video/generations')
            self.assertEqual(json.loads(server.calls[-1][2]), dict(model='video-v1', prompt='text', images=[], duration=10, aspect_ratio='9:16'))
            for model in ('video-v2', 'video-v2-fast'):
                client.create_task(model, 'text', [], params(duration=5, resolution='480p'))
                self.assertEqual(json.loads(server.calls[-1][2]), dict(model=model, prompt='text', images=[], videos=[], audios=[],
                    duration=5, aspect_ratio='9:16', resolution='480p', generate_audio=False))
            for model in sorted(V3_MODELS):
                client.create_task(model, 'text', [], params(resolution='720p', seed='4294967295'))
                self.assertEqual(json.loads(server.calls[-1][2]), dict(model=model, prompt='text', images=[], videos=[], audios=[],
                    duration=8, ratio='9:16', resolution='720p', generate_audio=False, seed=4294967295, bypass_face_check=False))

    def test_invalid_parameters_fail_without_any_network_request(self):
        cases = [
            ('MiniMax-H3', params(resolution='720p'), 'text', []),
            ('MiniMax-H3', params(duration=16), 'text', []),
            ('MiniMax-H3', params(aspect_ratio='7:5'), 'text', []),
            ('MiniMax-H3', params(duration=True), 'text', []),
            ('MiniMax-H3', params(duration=8.5), 'text', []),
            ('video-v1', params(duration=8), 'text', []),
            ('video-v1', params(duration=5, aspect_ratio='21:9'), 'text', []),
            ('video-v2', params(duration=8), 'text', []),
            ('video-v2-fast', params(duration=5, resolution='4K'), 'text', []),
            ('video-v2', params(duration=5, generate_audio='false'), 'text', []),
            ('video-v3', params(resolution='1080p'), 'text', []),
            ('seedance-2.5', params(resolution='720p', seed='4294967296'), 'text', []),
            ('video-v3', params(resolution='720p', seed='-1'), 'text', []),
            ('video-v3', params(resolution='720p'), '  ', []),
            ('MiniMax-H3', {}, 'text', []),
            ('MiniMax-H3', params(), 'text', ['https://example.com/image.jpg'] * 10),
        ]
        with LocalServer() as server:
            client = ApiClient(server.base, 'test'); self.addCleanup(client.close)
            for model, values, prompt, images in cases:
                with self.subTest(model=model, values=values, count=len(images)):
                    before = len(server.calls)
                    with self.assertRaises(ValueError):
                        client.create_task(model, prompt, images, values)
                    self.assertEqual(len(server.calls), before)

    def test_grok_real_multipart_and_multi_image_resolution_rejection(self):
        with LocalServer() as server, tempfile.TemporaryDirectory() as directory:
            first = Path(directory) / '中文1.png'; first.write_bytes(b'real-first-image')
            second = Path(directory) / '中文2.png'; second.write_bytes(b'real-second-image')
            client = ApiClient(server.base, 'test'); self.addCleanup(client.close)
            images = [str(first), str(second)]
            with self.assertRaises(ValueError):
                client.create_task(GROK, 'text', images, params())
            self.assertEqual(server.calls, [])
            client.create_task(GROK, 'text', images, params(resolution='720p', aspect_ratio='2:3'))
            body = server.calls[-1][2]
            self.assertEqual(body.count(b'name="input_reference"'), 2)
            self.assertIn(b'real-first-image', body)
            self.assertIn(b'real-second-image', body)
            for field in (b'seconds', b'resolution', b'aspect_ratio'):
                self.assertIn(b'name="' + field + b'"', body)
            self.assertNotIn(b'name="images"', body)

    def test_invalid_reference_urls_are_rejected_before_submission(self):
        with LocalServer() as server:
            client = ApiClient(server.base, 'test'); self.addCleanup(client.close)
            for reference in (None, '', 'C:/local.png', 'data:image/png;base64,abc', 'https:///missing-host'):
                with self.subTest(reference=reference), self.assertRaises(ValueError):
                    client.create_task('MiniMax-H3', 'text', [reference], params())
            self.assertEqual(server.calls, [])


class ModelWorkflowTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def test_all_model_dropdowns_preserve_documented_api_names(self):
        documented = ['video-v1', 'video-v2', 'video-v2-fast', 'video-v3', 'seedance-2.5',
                      'MiniMax-H3', 'grok-imagine-1.5-video', 'seedance2.5', 'sd-2.5', 'sd2.5']
        with tempfile.TemporaryDirectory() as directory, LocalServer() as server:
            config = ConfigManager(Path(directory) / 'config.json')
            card = ParamsCard(config); settings = SettingsPage(config, lambda *_: None)
            client = ApiClient(server.base, 'test-only'); self.addCleanup(client.close)
            try:
                for combo in (card.model, settings.default_model, settings.model_rows[0][2]):
                    self.assertEqual([combo.itemText(i) for i in range(combo.count())], documented)
                for model in documented:
                    card.model.setCurrentText(model)
                    settings.default_model.setCurrentText(model)
                    settings.model_rows[0][2].setCurrentText(model)
                    self.assertEqual(config.config['workspace']['model'], model)
                    self.assertEqual(config.config['defaults']['model'], model)
                    self.assertEqual(config.config['model_pool']['models'][0]['name'], model)
                    client.create_task(config.config['workspace']['model'], 'model name check', [], config.config['workspace'])
                    body = server.calls[-1][2]
                    if model == GROK:
                        self.assertIn(b'grok-imagine-1.5-video', body)
                    else:
                        self.assertEqual(json.loads(body)['model'], model)
            finally:
                card.close(); settings.close()

    def test_persisted_seedance_aliases_display_the_actual_submission_model(self):
        with tempfile.TemporaryDirectory() as directory:
            for model in ('seedance2.5', 'sd-2.5', 'sd2.5'):
                with self.subTest(model=model):
                    config = ConfigManager(Path(directory) / 'config.json')
                    config.config['workspace'].update(model=model, resolution='720p', duration=8)
                    config.config['defaults'].update(model=model, resolution='720p', duration=8)
                    card = ParamsCard(config); settings = SettingsPage(config, lambda *_: None)
                    try:
                        self.assertEqual(card.model.currentText(), model)
                        self.assertEqual(settings.default_model.currentText(), model)
                        self.assertEqual(card.duration.value(), 8)
                        self.assertTrue(card.audio.isEnabled())
                        self.assertEqual(config.config['workspace']['model'], model)
                    finally:
                        card.close(); settings.close()

    def test_ui_model_limits_and_h3_selection_persist(self):
        with tempfile.TemporaryDirectory() as directory:
            config = ConfigManager(Path(directory) / 'config.json')
            card = ParamsCard(config)
            settings = SettingsPage(config, lambda *_: None)
            try:
                card.model.setCurrentText('MiniMax-H3')
                self.assertEqual([card.resolution.itemText(i) for i in range(card.resolution.count())], ['480p', '768p', '1080p', '2K', '4K'])
                card.ratio.setCurrentText('9:16'); card.resolution.setCurrentText('1080p')
                self.assertIn('1088x1920', card.size_hint.text())
                self.assertEqual((card.duration.minimum(), card.duration.maximum()), (4, 15))
                self.assertFalse(card.audio.isEnabled())
                card.model.setCurrentText('video-v2')
                self.assertIn(card.duration.value(), (5, 10, 15))
                card.duration.setValue(8)
                self.assertIn(card.duration.value(), (5, 10, 15))
                card.model.setCurrentText('seedance-2.5')
                self.assertEqual([card.resolution.itemText(i) for i in range(card.resolution.count())], ['720p'])
                self.assertTrue(card.audio.isEnabled()); self.assertTrue(card.seed.isEnabled())
                settings.default_model.setCurrentText('MiniMax-H3')
                self.assertNotIn('720p', [settings.default_resolution.itemText(i) for i in range(settings.default_resolution.count())])
                settings.default_resolution.setCurrentText('768p')
                settings.default_ratio.setCurrentText('2:3')
                settings.default_model.setCurrentText('video-v3')
                settings.default_model.setCurrentText('MiniMax-H3')
                settings.default_ratio.setCurrentText('2:3')
                self.assertEqual(config.config['defaults']['aspect_ratio'], '2:3')
                card.model.setCurrentText('MiniMax-H3')
                card.resolution.setCurrentText('1080p')
                reopened = ConfigManager(config.path).load_config()
                self.assertEqual(reopened['workspace']['resolution'], '1080p')
                self.assertEqual(reopened['defaults']['resolution'], '768p')
                self.assertEqual(reopened['defaults']['aspect_ratio'], '2:3')
            finally:
                card.close(); settings.close()

    def test_worker_rejects_invalid_parameters_and_empty_prompt_before_upload(self):
        with LocalServer() as server, tempfile.TemporaryDirectory() as directory:
            root = Path(directory); prompt = root / '1.txt'; image = root / '1.png'
            prompt.write_text('test', encoding='utf-8'); image.write_bytes(b'good-image')
            config = copy.deepcopy(DEFAULT_CONFIG)
            config['paths'] = dict(prompts=directory, images=directory, output=str(root / 'output'))
            config['api'].update(base_url=server.base, upload_url=server.base + '/upload', api_key='test')
            config['workspace'].update(model='MiniMax-H3', resolution='720p')
            worker = TaskWorker(config, []); logs = []
            worker.log_message.connect(lambda message, level: logs.append((message, level)))
            worker.run()
            self.assertEqual(server.calls, [])
            self.assertEqual(worker.tasks[0]['status'], 'failed')
            self.assertTrue(any('参数校验' in message and level == 'error' for message, level in logs))
            config['workspace']['resolution'] = '1080p'; prompt.write_text('  ', encoding='utf-8')
            worker = TaskWorker(config, []); worker.run()
            self.assertEqual(server.calls, [])
            self.assertEqual(worker.tasks[0]['status'], 'failed')

    def test_h3_fixed_size_ratio_change_is_a_distinct_generation(self):
        with LocalServer() as server, tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / '1.txt').write_text('test', encoding='utf-8'); (root / '1.png').write_bytes(b'good-image')
            config = copy.deepcopy(DEFAULT_CONFIG)
            config['paths'] = dict(prompts=directory, images=directory, output=str(root / 'output'))
            config['api'].update(base_url=server.base, upload_url=server.base + '/upload', api_key='test')
            config['workspace'].update(model='MiniMax-H3', resolution='1080p', aspect_ratio='16:9', poll_interval=.01)
            first = TaskWorker(config, []); first.run()
            config['workspace']['aspect_ratio'] = '9:16'
            second = TaskWorker(config, first.tasks); second.run()
            self.assertNotEqual(first.tasks[0]['task_id'], second.tasks[0]['task_id'])
            self.assertEqual([json.loads(body)['size'] for path, _, body in server.calls if path == '/videos'], ['1920x1088', '1088x1920'])

    def test_v3_effective_audio_seed_changes_submit_and_poll_only_changes_do_not(self):
        with LocalServer() as server, tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / '1.txt').write_text('text', encoding='utf-8'); (root / '1.png').write_bytes(b'good-image')
            config = copy.deepcopy(DEFAULT_CONFIG)
            config['paths'] = dict(prompts=directory, images=directory, output=str(root / 'output'))
            config['api'].update(base_url=server.base, upload_url=server.base + '/upload', api_key='test')
            config['workspace'].update(resolution='720p', poll_interval=.01)
            first = TaskWorker(config, []); first.run()
            config['workspace']['generate_audio'] = False
            second = TaskWorker(config, first.tasks); second.run()
            config['workspace']['seed'] = '123'
            third = TaskWorker(config, second.tasks); third.run()
            self.assertEqual(len({w.tasks[0]['task_id'] for w in (first, second, third)}), 3)
            calls = len(server.calls)
            config['workspace'].update(seed='00123', poll_interval=.05, max_retries=9)
            fourth = TaskWorker(config, third.tasks); fourth.run()
            self.assertEqual(len(server.calls), calls)
